<?php 

/**
 * Implement hook_form_alter()
 */ 

function regform_alter_form_alter(&$form, &$form_state, $form_id){
    if(!($form_id == 'user_register_form' || $form_id == 'user_profile_form')) {
        return;
    }
    $form['accept_terms'] = array(
        '#type' => 'checkbox',
        '#description' => t('By registering at %site-name, you agree that at any time, we can enter your home.', 
            array('%site-name' => variable_get('site_name', 'drupal'))),
        '#default_value'=> FALSE,
        '#title' => 'Check me!',
    );
}